version: '3.9'
services:
  postgres_test:
    build: ./postgres
    ports:
      - "29901:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwe123
    volumes:
      - db_data_test:/var/lib/postgresql/data

  backend_test:
    build: ./backend
    volumes:
      - type: bind
        source: ./backend/src
        target: /app/src
    ports:
      - "3100:3100"
    depends_on:
      - postgres_test
    restart: always
    environment:
      - TSC_WATCHFILE=UseFsEvents
      - TYPEORM_HOST=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=ivan
      - DATABASE_PASSWORD=123qwe
      - DATABASE_DATABASE=ivan
      - DATABASE_SYNC=true
      - DATABASE_DROP_SCHEMA=false
      - DATABASE_RUN_MIGRATIONS=true
      - DATABASE_LOGGING=true

    command:
      - sh
      - -c
      - |
        (npm run test:e2e)
volumes:
  db_data_test:

